### ISSUE TITLE
Role name and path combined, should not be above 64 characters

### ISSUE THREAD

**Issue by isen-ng** [traveloka/terraform-aws-iam-role#28]
See: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html#reference_iam-limits-entity-length

> Important
>
> If you intend to use a role with the Switch Role feature in the AWS console, then the combined Path and RoleName cannot exceed 64 characters.

Unfortunately, I have this use case. When I want to give a role access to administer an EKS cluster, I follow this guide of adding user's into the cluster:
https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html

Although not explicitly stated in the EKS document, I discovered that any roles created with this module will not be able to access the cluster, no matter what I do. However, other common roles like the SuperAdmin, PowerUser and even ReadOnly roles can access the EKS cluster when added to `aws-auth` according to the guide.

Upon further, research I discovered that only roles with combined path and name less than 64 characters can access the cluster.

I propose that the path variable be also set to `/`, role name to be descriptive, and the service types, and etc to be saved under tags. Reasons are:

1. Role paths are only for grouping roles according to [this](https://stackoverflow.com/questions/46324062/in-aws-iam-what-is-the-purpose-use-of-the-path-variable). The same purpose can be achieved by tagging
2. Keeping role path and name's combined path to less than 64 characters will allow your module to support role switching
3. If the role name is descriptive enough, searching for it will be already easy.

**Comment by rafikurnia** [comment]
Hi @isen-ng, thanks for opening issue and PR.. I really appreciate that.. Also thanks for the suggestion regarding role path, I want to learn more about it.

> However, other common roles like the SuperAdmin, PowerUser and even ReadOnly roles can access the EKS cluster when added to aws-auth according to the guide.
Is it because those roles not having `/service-role/` in their path? Or because their path + name doesn't exceed 64 characters?

**Comment by sshvetsov** [comment]
Thanks for PR @isen-ng.
First of all I'm a bit confused by your intentions, since "service roles" are intended to be assumed by AWS services, not humans. Since role created by this module are not intended for humans to assume, you should never have to list these roles with Switch Role feature in AWS Console.

Despite what someone on Stack Overflow thinks, role path is useful for more than just "grouping roles". Path provides additional structure to control users' access to principals and permissions. Unlike role path and name, tags are less suitable for this purpose, because they are mutable.

I'm afraid I have to decline your proposal, as "service module" does exactly what it was designed to do: i.e. create a role for AWS service, not humans, to assume.

You might want to consider using [User](https://github.com/traveloka/terraform-aws-iam-role/tree/master/modules/user) module, if you intentions are to allow humans to assume role. Roles create with that module contain short '/' path by default and I suspect will satisfy your requirements better.

**Comment by isen-ng** [comment]
@sshvetsov 
Thank you for your explanation!

Let me explain what i'm trying to achieve, then maybe you can suggest something I can do to fulfil it.

Situation:

1. I'm trying to install some required services (our continuous deployment service) on the EKS cluster we have just created.
  1.1. The EKS cluster was created using terraform
  1.2. The script to install these services are also in terraform for the fact that ansible has horrible support for installing stuff on kubernetes
2. This installation process is done in a codebuild project, as part of our IAC pipeline.
  2.1 We are using https://github.com/traveloka/terraform-aws-codebuild-terraform-ci-cd
3. The codebuild project terraform creates a "service" account using `terraform-aws-iam-role` module

Problem:

1. The codebuild project's role is unable to administrate the EKS cluster to install the services
2. And because the combined path + name is > than 64 characters, mapping the codebuild's service role into the EKS cluster using aws-auth does not work
  2.2 This means that the codebuild project is unable to install stuff on the EKS cluster


What is the recourse for this type of situation? This is not a situation involving a real human.
Perhaps I should create a "machine user" role using the User module in iam-roles and have the codebuild project's role assume this machine user role? Is that even possible?

**Comment by sshvetsov** [comment]
I think this issue is outside of the scope of this module. As I understand it, you are having problems with `terraform-ci-cd` module, its use of this service module for the CodeBuild project, and because EKS aws-auth doesn't seem to support path+name combination longer than 64 chars. As far as I can tell, the role this module generates is fully compliant with [IAM Role API constraints](https://docs.aws.amazon.com/IAM/latest/APIReference/API_Role.html).

Sounds like the root of the problem is with EKS aws-auth rejecting a role with perfectly compliant path and name. This maybe a bug in their implementation (I have seen other AWS service teams forget about existence of `path` before). I recommend that you open a support case with AWS, as there is no good reason why a perfectly formed role ARN should be rejected by EKS aws-auth.

Alternatively, you should be able to use AWS CLI and STS service to assume another role from inside of the CodeBuild project. Perhaps even simpler option would be use Terraform to assume another role as part of [provider configuration](https://www.terraform.io/docs/providers/aws/index.html#assume-role).

I'm closing this issue as "wontfix".
